<?php

namespace Vibalco\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CurrencyExchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyExchangeRepository extends EntityRepository
{
    /**
     * Return first row of day requested
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLastCurrency() {
        $dql = "
            SELECT ce
            FROM MainBundle:CurrencyExchange ce
            WHERE ce.retrievedAt >= :todayStart
                AND ce.retrievedAt < :todayEnd
        ";
        $today = new \DateTime('now');
        $yesterday = clone $today;
        $yesterday->modify('-1 day');
        $em = $this->getEntityManager();
        $query = $em->createQuery($dql)
            ->setFirstResult(0)
            ->setMaxResults(1)
            ->setParameter('todayStart', $yesterday->format('Y-m-d') . ' 00:00:00')
            ->setParameter('todayEnd', $today->format('Y-m-d') . ' 23:59:00');
        try
        {
            return $query->getSingleResult();
        }
        catch (NoResultException $ex)
        {

        }

        return null;
    }
}
